name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish_to_npm:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Check if version bump
        id: check
        uses: EndBug/version-check@095362f3cd50f690c8fa0e6afeea81834bd8d320 # v3.0.0

      - name: Log when unchanged
        if: steps.check.outputs.changed != 'true'
        run: echo "No version change"

      - name: Install deps
        if: steps.check.outputs.changed == 'true'
        run: yarn
        env:
          CI: true

      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: yarn build
        env:
          CI: true

      - name: Set NPM Token
        if: steps.check.outputs.changed == 'true'
        uses: filipstefansson/set-npm-token-action@8c885037600dcbc26b36df817527ec85ab4f58ac # v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish new version
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
